
package View;

import Controller.InsertController;

/**
 *
 * @author dasun_weerawardhana
 */
public class AddDoctor extends javax.swing.JFrame {

    /**
     * Creates new form AddDoctor
     */
    public AddDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DNIC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DContact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        DConfirm = new javax.swing.JPasswordField();
        DRegisterBtn = new javax.swing.JButton();
        DClearBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        DReg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DEligibility = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DSpecialize = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Doctor Details Manager");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 610, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        DName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(DName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 380, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("NIC:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        DNIC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(DNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 380, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Contact No:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        DContact.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        DContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DContactActionPerformed(evt);
            }
        });
        jPanel2.add(DContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 380, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("User Name:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        DUser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(DUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 380, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        DPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(DPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 380, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Confirm:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        DConfirm.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(DConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 380, -1));

        DRegisterBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DRegisterBtn.setText("Register");
        DRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRegisterBtnActionPerformed(evt);
            }
        });
        jPanel2.add(DRegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 270, -1));

        DClearBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DClearBtn.setText("Clear all");
        DClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DClearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(DClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Reg No :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        DReg.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(DReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 380, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Specialized In :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        DEligibility.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        DEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEligibilityActionPerformed(evt);
            }
        });
        jPanel2.add(DEligibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 380, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Eligibility:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        DSpecialize.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        DSpecialize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Specialize in various fields select here", "Cardiology (heart)", "Dermatology (skin)", "Endocrinology (hormones)", "Gastroenterology (digestive system)", "Neurology (nervous system)", "Ophthalmology (eyes)", "Orthopedics (musculoskeletal system)", "Pediatrics (children)", "Psychiatry (mental health)", "Radiology (medical imaging)" }));
        DSpecialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSpecializeActionPerformed(evt);
            }
        });
        jPanel2.add(DSpecialize, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 380, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/doctor.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 640));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRegisterBtnActionPerformed
        // TODO add your handling code here:  
        String special = DSpecialize.getSelectedItem().toString();
        
        InsertController.InsertDoctorDetails(DName.getText(),DNIC.getText(),DReg.getText(),DEligibility.getText(),special,DContact.getText(),DUser.getText(),DPassword.getText(),DConfirm.getText());
        clearField();
        
        
        DoctorLogin back = new DoctorLogin();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_DRegisterBtnActionPerformed
  public void clearField() {
        DName.setText("");
        DNIC.setText("");
        DEligibility.setText("");
        DContact.setText("");
        DUser.setText("");
        DPassword.setText("");
        DConfirm.setText("");
    }
    private void DContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DContactActionPerformed

    private void DEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEligibilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEligibilityActionPerformed

    private void DClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DClearBtnActionPerformed

    private void DSpecializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSpecializeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DSpecializeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DClearBtn;
    private javax.swing.JPasswordField DConfirm;
    private javax.swing.JTextField DContact;
    private javax.swing.JTextField DEligibility;
    private javax.swing.JTextField DNIC;
    private javax.swing.JTextField DName;
    private javax.swing.JPasswordField DPassword;
    private javax.swing.JTextField DReg;
    private javax.swing.JButton DRegisterBtn;
    private javax.swing.JComboBox<String> DSpecialize;
    private javax.swing.JTextField DUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
