/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.InsertController;

/**
 *
 * @author dasun_weerawardhana
 */
public class AddReception extends javax.swing.JFrame {

    /** Creates new form AddReception */
    public AddReception() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RNIC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RContact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        RRegBtn = new javax.swing.JButton();
        RClearBtn = new javax.swing.JButton();
        RConfirm = new javax.swing.JPasswordField();
        BackBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reception Details Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 669, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        RName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(RName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 340, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("NIC:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        RNIC.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(RNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 340, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Contact Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        RContact.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        RContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RContactActionPerformed(evt);
            }
        });
        jPanel1.add(RContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 340, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("User Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        RUser.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(RUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 340, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        RPassword.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        RPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(RPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 340, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Confirm:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        RRegBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        RRegBtn.setText("Register");
        RRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRegBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RRegBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 188, 50));

        RClearBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        RClearBtn.setText("Clear all");
        RClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RClearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, -1, -1));

        RConfirm.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        RConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(RConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 340, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/reception.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRegBtnActionPerformed
        // TODO add your handling code here:
        InsertController.InsertRecepDetails(RName.getText(), RNIC.getText(), RContact.getText(), RUser.getText(), RPassword.getText(), RConfirm.getText());
        clearField();
        ReceptionLogin back = new ReceptionLogin();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_RRegBtnActionPerformed
        public void clearField() {
        RName.setText("");
        RNIC.setText("");
        RContact.setText("");
        RUser.setText("");
        RPassword.setText("");
        RConfirm.setText("");
       
    }    
    private void RClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RClearBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_RClearBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        ReceptionLogin back = new ReceptionLogin();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void RContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RContactActionPerformed

    private void RPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RPasswordActionPerformed

    private void RConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReception().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton RClearBtn;
    private javax.swing.JPasswordField RConfirm;
    private javax.swing.JTextField RContact;
    private javax.swing.JTextField RNIC;
    private javax.swing.JTextField RName;
    private javax.swing.JPasswordField RPassword;
    private javax.swing.JButton RRegBtn;
    private javax.swing.JTextField RUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
