
package View;

import Controller.InsertController;


public class RegisterPatient extends javax.swing.JFrame {

    
    public RegisterPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FNameTF = new javax.swing.JTextField();
        LNameTF = new javax.swing.JTextField();
        NICTF = new javax.swing.JTextField();
        DOBTf = new javax.swing.JTextField();
        MaleTF = new javax.swing.JRadioButton();
        FemaleTF = new javax.swing.JRadioButton();
        AddressTF = new javax.swing.JTextField();
        ContactTF = new javax.swing.JTextField();
        BTypeCMB = new javax.swing.JComboBox<>();
        SubmitBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        ADPHBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setText("Register patient Application");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("First Name:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Last Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("NIC:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Date of Birth:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Gender:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Address:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Contact:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Blood Type:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 180, -1));

        FNameTF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(FNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 280, 31));

        LNameTF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(LNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 280, 30));

        NICTF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(NICTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 280, 30));

        DOBTf.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(DOBTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 280, 30));

        buttonGroup1.add(MaleTF);
        MaleTF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MaleTF.setText("Male");
        jPanel2.add(MaleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 110, -1));

        buttonGroup1.add(FemaleTF);
        FemaleTF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        FemaleTF.setText("Female");
        jPanel2.add(FemaleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 110, -1));

        AddressTF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(AddressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 280, -1));

        ContactTF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(ContactTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 280, -1));

        BTypeCMB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BTypeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        BTypeCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTypeCMBActionPerformed(evt);
            }
        });
        jPanel2.add(BTypeCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 100, -1));

        SubmitBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 180, -1));

        ClearBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ClearBtn.setText("Clear all");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 660, 160, -1));

        ADPHBtn.setText("HOME");
        ADPHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADPHBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ADPHBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/regpatient.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        String gender=null;
        if(MaleTF.isSelected()){
            gender="Male";
        }
        else if(FemaleTF.isSelected()){
            gender="Female";
        }
        
        String Btype = BTypeCMB.getSelectedItem().toString();
        
        InsertController.InsertPatient(FNameTF.getText(),LNameTF.getText(), NICTF.getText(), DOBTf.getText(), gender, AddressTF.getText(), ContactTF.getText(),Btype );
        
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void ADPHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADPHBtnActionPerformed
        // TODO add your handling code here:
        ReceptionHome back = new ReceptionHome();
        back.setVisible(true);
        super.dispose();
        clearField();
    }//GEN-LAST:event_ADPHBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void BTypeCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTypeCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTypeCMBActionPerformed
    
    public void clearField(){
        FNameTF.setText("");
        LNameTF.setText("");
        NICTF.setText("");
        DOBTf.setText("");
        MaleTF.setSelected(false);
        FemaleTF.setSelected(false);
        AddressTF.setText("");
        ContactTF.setText("");
        BTypeCMB.setSelectedItem(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADPHBtn;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JComboBox<String> BTypeCMB;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField ContactTF;
    private javax.swing.JTextField DOBTf;
    private javax.swing.JTextField FNameTF;
    private javax.swing.JRadioButton FemaleTF;
    private javax.swing.JTextField LNameTF;
    private javax.swing.JRadioButton MaleTF;
    private javax.swing.JTextField NICTF;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
