
package View;

import Model.DBSearch;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


public class ViewPatient01 extends javax.swing.JFrame {

    
    public ViewPatient01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PFNameTF = new javax.swing.JTextField();
        PLNameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PNICTF = new javax.swing.JTextField();
        PBirthTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GenderTF = new javax.swing.JTextField();
        BTypeTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AddressTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PContactTF = new javax.swing.JTextField();
        VHBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View patient details 01");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 670, 63));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        PFNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(PFNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 290, -1));

        PLNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PLNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(PLNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 290, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIC:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 70, -1));

        PNICTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(PNICTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 290, -1));

        PBirthTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(PBirthTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 290, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Birth Day :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, 26));

        GenderTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(GenderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 290, -1));

        BTypeTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTypeTFActionPerformed(evt);
            }
        });
        jPanel1.add(BTypeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 290, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Blood Type:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        AddressTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AddressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 290, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Addres:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        PContactTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PContactTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PContactTFActionPerformed(evt);
            }
        });
        jPanel1.add(PContactTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 290, -1));

        VHBtn.setText("View History");
        VHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHBtnActionPerformed(evt);
            }
        });
        jPanel1.add(VHBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));

        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/viewpatint01.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHBtnActionPerformed
        // TODO add your handling code here:
        ResultSet r = new DBSearch().SearchHistory(PNICTF.getText());
        try{
            ViewPatientHistory view = new ViewPatientHistory();
            
            view.NameTF.setText(PFNameTF.getText());
            view.NICTF.setText(PNICTF.getText());
            DefaultTableModel dtm = (DefaultTableModel)view.ViewHistoryTable.getModel();
            dtm.setRowCount(0);
            
            Vector v;
            while (r.next()){
                    v = new Vector();
                    v.add(r.getString("Clinic"));
                    v.add(r.getString("Date"));
                    v.add(r.getString("Time"));
                    v.add(r.getString("Amount"));
                    dtm.addRow(v);
            }
            view.setVisible(true);
            //super.dispose();
        }
        catch(SQLException e){
         
        }
    }//GEN-LAST:event_VHBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        ReceptionHome back = new ReceptionHome();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void PContactTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PContactTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PContactTFActionPerformed

    private void BTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTypeTFActionPerformed

    private void PLNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PLNameTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatient01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatient01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatient01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatient01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatient01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AddressTF;
    public javax.swing.JTextField BTypeTF;
    public javax.swing.JTextField GenderTF;
    private javax.swing.JButton HomeBtn;
    public javax.swing.JTextField PBirthTF;
    public javax.swing.JTextField PContactTF;
    public javax.swing.JTextField PFNameTF;
    public javax.swing.JTextField PLNameTF;
    public javax.swing.JTextField PNICTF;
    private javax.swing.JButton VHBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
